---
- name: Playbook
  hosts: all
  become: true
  become_user: root
  tasks:
   - name : Install updates using yum
     yum:
      name: "*"
      state: latest
      exclude: docker*,containerd.io*
   - name: Install Git
     yum: 
      name: git 
      state: present  
   - name: Clone the Git repository
     git:
      repo: 'https://github.com/Sumanth17-git/JavaProject.git'
      accept_hostkey: yes
      clone: yes
      dest: /home/ansible/JavaProject
      force: yes
