---
- name: Playbook
  hosts: all
  become: true
  become_user: root
  tasks:
   - name: Install httpd package
     yum: 
      name=httpd 
      state=latest
   - name: Copy index.html file
     copy: 
      src=/home/ansible/index.html 
      dest=/var/www/html
     notify:
      - restart httpd
   - name: Start httpd service
     service: 
      name=httpd 
      state=started 
      enabled=yes
  handlers:
   - name: restart httpd
     service: 
      name=httpd 
      state=restarted
